### PR TITLE
Event flow for program students

### PR DESCRIPTION
**Pull request by me97esn**

### CODE REVIEW

**Comment by me97esn** [comment]
This PR contains information about the event flow, and the messages produced by Ladok, for Program. 
It includes no logic.

**Review by jhsware — CHANGES_REQUESTED** [review]
Given that we work with JSON and not XML, I suggest we store messages as JSON-data rather than XML.

**Comment by me97esn** [comment]
> Given that we work with JSON and not XML, I suggest we store messages as JSON-data rather than XML.
I don't agree. Given that the original messages are in XML format from Ladok, we shouldn't change the original messages with the risk of introducing errors

**Review by jhsware — COMMENTED** [review]
Do we need to look att specialisations too? Given the nested nature of kurspaketeringar.

**Comment by me97esn** [comment]
> Do we need to look att specialisations too? Given the nested nature of kurspaketeringar.

That is a good question. We haven't done anything with specialisations so far, and have no plan on doing it in the near future.
I suggest we _don't_ do it now

**Pull request merged**
